version: "2.2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - orders_network
  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - orders_network
  backend:
    build: ./backend
    container_name: orders_api
    networks:
      - orders_network
    ports:
      - 8080:8080
networks:
  orders_network:
